### ISSUE TITLE
Change packing queue based on router

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-server#44]
MR to master

* add a virtual field to return objects: `destination: String` which will be either `"CUSTOMER" | "VENDOR"`
* add a virtual field to return objects `destinationCode: Number` which will be `"${destination}-${stepCode}"`
* add field to packingSlip schema `destinationCode: Number` (same as above)
* Create an arbitrary number of entries for each work order item based on router steps that are from category "Shipping"
* If the step name is not equal to `"Ship To Customer"` assume it is a vendor shipment; i.e. only the final shipment is a "Customer" shipment

Changes to packingSlip
* When creating a packing slip insert the `destinationCode`
* When aggregating Fulfilled Qty - group & add qties based on `destinationCode`

Edge cases:
* If item d/n have a router, insert `destination: "CUSTOMER"`
* If the last shipping step of a router is NOT "Ship To Customer", do NOT insert a customer destination, simply assume the vendor destination will be the last stop

**Comment by mitchell-mccracken** [comment]
should we assume that all jobs are released at this point? (meaning they will have step codes assigned)

**Comment by mitchell-mccracken** [comment]
Also I think `destinationCode` should be type `String`
