### ISSUE TITLE
Add /search endpoint to /packingSlips

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-server#7]
To be able to quickly find what parts were packed in which packing slip

should function the same as shipments

**Comment by joshplumley** [comment]
@jarrilla, I was going to tackle https://github.com/conturo-prototyping/pack-ship-client/issues/13, but noticed it needs this issue completed first. Is it OK if we take backend issues as well?

**Comment by jarrilla** [comment]
Yea absolutely. Go for it

**Comment by joshplumley** [comment]
Do you want to edit the current search packing slip end point or create a new one? There is one in place for shipment and customer id. My original plan was to edit this one to take an order number or a part number.

**Comment by jarrilla** [comment]
might be better to create a new endpoint since this one seems to work exactly as necessary when fetching information for shipment editing
