### ISSUE TITLE
shpiment PDF function should be...

### ISSUE THREAD

**Issue by jarrilla** [conturo-prototyping/pack-ship-server#8]
a collective of all packing slip tables that are included in the shipment.
Each should be its own document with header that shows the packing slip id

**Comment by jarrilla** [comment]
ALSO: when pulling a PDF for a shipment that was either DROP-OFF or LOCAL DELIVERY there should be a separate sign-off line for "received by"

**Comment by joshplumley** [comment]
@jarrilla, any template on what the final pdf should look like?

**Comment by jarrilla** [comment]
You can leave this one to me. It's quick enough to do and it's mostly done. I just forgot to assign myself to the issue

**Comment by jarrilla** [comment]
@mitchell-mccracken 
* Remove the last page that aggregates all shipped to date
* First populate all packing slips that are included in the shipment
* Group the items in the shipment by `{ [workOrderItem._id]: { orderedQty: Number, shipQty: Number } }` where shipQty will be `$sum` and `orderQty` will be `$first` (orderQty is in some cases referred to as batchQty).
